// Eigener Karten-Pool. __ markiert die Lücke, die durch die gespielte weiße Karte ersetzt wird.
// Falls keine Lücke vorhanden ist, wird die Antwort hinten drangehängt.

const blackCards = [
  "Was steckt hinter Tür Nummer 3? __",
  "Worüber sollte mein TED Talk gehen? __",
  "Was ist die wahre Ursache des Klimawandels? __",
  "Was bringt jede Familienfeier zum Eskalieren? __",
  "Was würde Mama niemals zugeben? __",
  "Was steht heimlich in meinem Lebenslauf? __",
  "Was hat mich aus dem Schützenverein fliegen lassen? __",
  "Was finde ich entspannender als Yoga? __",
  "Was war der Grund für meine Scheidung? __",
  "Was ist das hässlichste Geschenk, das ich je bekommen habe? __",
  "Wovor fürchten sich kleine Kinder zurecht? __",
  "Was ist das neue Statussymbol der Boomer? __",
  "Mein Therapeut sagt, ich habe ein Problem mit __.",
  "Was hat es nicht in den Bibel-Cut geschafft? __",
  "Was geht mir auf einer Beerdigung durch den Kopf? __",
  "Worauf bin ich seit Jahren süchtig? __",
  "Was wirft Oma immer in den Wäschetrockner? __",
  "Was hat die Bundeswehr aus mir gemacht? __",
  "Was würde Jesus heute zur Begrüßung sagen? __",
  "Was steht ganz oben auf der To-Do-Liste eines mittelmäßigen Bösewichts? __",
  "Was hat das Christkind dieses Jahr unterm Baum vergessen? __",
  "Was ist der wahre Sinn des Lebens? __",
  "Was sollte definitiv NICHT auf einer Hochzeitstorte stehen? __",
  "Was ist das nächste große Dating-App-Feature? __",
  "Was würde Olaf Scholz auf seine Visitenkarte drucken? __",
  "Was ist deutscher als Bratwurst? __",
  "Was kommt als Nächstes auf Netflix? __",
  "Was bringt mich morgens aus dem Bett? __",
  "Was hat Hape Kerkeling in seiner Garage versteckt? __",
  "Was war früher besser? __",
  "Was hat mein Schwiegervater nach drei Jägermeister gestanden? __",
  "Was ist das echte Geheimnis hinter der Pyramidenform? __",
  "Was hilft gegen Schluckauf? __",
  "Womit erpresse ich meinen Bruder? __",
  "Was steht im Tagebuch von Markus Söder? __",
  "Was sollte man nicht vor Kindern sagen? __",
  "Was riecht im Lehrerzimmer? __",
  "Was hat sich nach dem fünften Glühwein selbständig gemacht? __",
  "Was ist Heidi Klums neuestes Hobby? __",
  "Was ist der Grund, warum ich heute zu spät bin? __",
  "Was hat mein Hund gestern gegessen? __",
  "Was würde mich sofort zum YouTube-Star machen? __",
  "Mein Kindheitstrauma: __.",
  "Was hat den letzten Bachelor-Cast überzeugt? __",
  "Was ist die geheime Zutat in Großmutters Kuchen? __",
  "Was ist im Universum eines Vier-Sterne-Generals normal? __",
  "Was bedeutet \"deutsche Gemütlichkeit\"? __",
  "Was hat den Fall der Berliner Mauer wirklich ausgelöst? __",
  "Was ist der wahre Grund, warum ich keinen Sex mehr habe? __",
  "Was sollte unbedingt in jedes Schulgebet aufgenommen werden? __",
  "Was würde ich tun, wenn ich für einen Tag unsichtbar wäre? __",
  "Was ist das Problem mit der jüngeren Generation? __",
  "Was sehe ich, wenn ich die Augen schließe? __",
  "Was steht auf meinem Grabstein? __",
  "Eine Sache, die jedes Erstdate ruiniert: __.",
  "Mein größter Fehler war __.",
  "Was hat der Papst Donnerstag gemacht? __",
  "Was ist der Grund für mein soziales Unbehagen? __",
  "Auf was würde ich für 10 Euro verzichten? __",
  "Was ist die wahre Ursache für meinen Burnout? __",
  "Was ist die wahre Erklärung für meinen schlechten Schlaf? __",
  "Was hat der Pfarrer in der Beichte gehört? __",
  "Was ist der Inhalt von Friedrich Merz' Aktentasche? __",
  "Was hat Habeck heimlich auf seinem Spotify-Wrapped? __",
  "Was würde mich auf einer Klassenfahrt sofort outen? __",
  "Was ist meine Abschiedsbotschaft an die Welt? __",
  "Worüber redet man auf einer schwedischen Beerdigung? __",
  "Was darf auf keinem Kirchentag fehlen? __",
  "Was steht auf der Speisekarte vom Höllen-Bistro? __",
  "Was hat mich aus der Pfadfindergruppe fliegen lassen? __",
  "Was hat sich Greta Thunberg insgeheim gewünscht? __",
  "Was tausche ich gegen meine Seele? __",
  "Was ist auf dem Parteitag der CDU passiert? __",
  "Was darf man niemals googeln? __",
  "Was ist der Plot meines geplanten Tatorts? __",
  "Was kommt aus der Nase von Donald Trump? __",
  "Was bedeutet \"erwachsen sein\"? __",
  "Wofür braucht jeder gute Erotikladen __?",
  "Was hat Kim Jong-un beim Frühstück bestellt? __",
  "Was ist der Grund warum ich nicht mehr aufs Schützenfest gehe? __",
  "Was steht in der unveröffentlichten Autobiografie von Boris Becker? __",
  "Was ist das Geheimnis hinter Heidi Klums ewiger Faltenfreiheit? __",
  "Was hat mein Chef in meiner Personalakte notiert? __",
  "Was findet sich nach 2 Wochen Festival in der Hose? __",
  "Was schreibt man in eine Trauerkarte für Nachbarn? __",
  "Was ist der Inhalt einer typischen Bundeswehr-Tüte? __",
  "Was steht im Reisebericht des Papstes? __",
  "Was hat den Bundespräsidenten richtig sauer gemacht? __",
  "Was ist die wahrste aller Verschwörungstheorien? __",
  "Was ist der Top-Hit auf dem Schlagerschiff? __",
  "Was tue ich heimlich auf Beerdigungen? __",
  "Was findet man im Briefkasten von Markus Söder? __",
  "Was ist Olaf Scholz' Lieblings-Cocktailrezept? __",
  "Was bekomme ich von meiner Tante zur Konfirmation? __",
  "Was ist der typische Reichsbürger-Beweis gegen die BRD? __",
  "Was ist mein Burnout-Trigger Nr. 1? __",
  "Womit erpresse ich meinen Personalchef? __",
  "Was ist der Grund, warum mein Online-Date plötzlich verschwunden ist? __",
  "Was macht Andrea Berg backstage? __",
  "Was ist der heimliche Liebling jedes Religionslehrers? __",
  "Was finde ich plötzlich attraktiv ab 30? __",
  "Was bedeutet wahre Liebe für mich? __",
  "Was ist Sahra Wagenknechts Geheimwaffe? __",
  "Was sollte man niemals unter dem Mistelzweig anstellen? __",
  "Was hat die Polizei bei der Razzia in der WG gefunden? __",
  "Worüber lacht die Queen im Himmel? __",
  "Was ist die wahre Bedeutung von \"Heimatliebe\"? __",
  "Was hat sich Elon Musk dieses Mal ausgedacht? __",
  "Was steht hinter dem Vorhang im Bordell? __",
  "Was ist das Geheimrezept für eine ESC-Performance? __",
  "Was hat Mama in meinem Kinderzimmer entdeckt? __",
  "Was war mein traumatischster Kindheitsmoment? __",
  "Was nervt am Bauernhof-Urlaub? __",
  "Was finde ich eklig, kann aber nicht aufhören? __",
  "Was kommt nach dem dritten Tequila-Shot? __",
  "Was bedeutet \"Work-Life-Balance\" für mich? __",
  "Was ist auf der Setlist des nächsten Helene-Fischer-Konzerts? __",
  "Was ist die wahre Bedeutung von Weihnachten? __",
  "Was hat es nicht ins ARD-Programm geschafft? __",
  "Was ist das Seltsamste, das ich auf Tinder erlebt habe? __",
  "Was lerne ich gerade auf YouTube? __",
  "Was ist Joko und Klaas' nächster Stunt? __",
  "Was findet man auf eBay-Kleinanzeigen? __",
  "Was hat Friedrich Merz unterm Kissen versteckt? __",
  "Was ist der heimliche Kink meines Lehrers? __",
  "Was hat den letzten Bundestrainer gefeuert? __",
  "Was bedeutet \"Pflegekraft mit Berufung\"? __",
  "Was sollte man niemals seiner Schwiegermutter erzählen? __",
  "Was ist im Geheimfach von Omas Handtasche? __",
  "Was findet man in der Schublade meines Mathelehrers? __",
  "Worauf masturbiert ein Ehepaar nach 20 Jahren noch? __",
  "Was steht im Polizeibericht von gestern Nacht? __",
  "Was ist mein peinlichster Suchverlauf? __",
  "Was hat Karl Marx im Café bestellt? __",
  "Was bedeutet \"spirituell\" im Tinder-Profil? __",
  "Was hat Angela Merkel im Ruhestand entdeckt? __",
  "Was ist das Schlimmste, was im Beichtstuhl rauskommen kann? __",
  "Womit ködert man eine Frühvegane? __",
  "Was hat Gott nach dem 7. Tag noch erschaffen? __",
  "Was hat der Apotheker mir wirklich verkauft? __",
  "Was steht im Drehbuch der nächsten \"Bauer sucht Frau\"-Folge? __",
  "Was ist der Tiefpunkt einer Mallorca-Tour? __",
  "Was haben Putin und Trump gemeinsam? __",
  "Was ist das peinlichste, das in einer langen Beziehung passiert? __",
  "Was ist mein letzter Atemzug? __",
  "Was hat sich in der WhatsApp-Familiengruppe als Skandal entpuppt? __",
  "Was ist das Beste an Single-Sein? __",
  "Was ist das Wichtigste in einer Polyamorie-WG? __",
  "Was ist mein neuer Lebensinhalt? __",
  "Was steht ungesehen in meinem Browserverlauf? __",
  "Was hat der Therapeut nach 2 Stunden mit mir aufgegeben? __",
  "Was ist der Plot meines OnlyFans? __",
  "Was hat den Kindergeburtstag eskaliert? __",
  "Was ist der wahre Grund für die Energiewende? __",
  "Was ist Friedrich Merz' wahres Wahlversprechen? __",
  "Was generiert ChatGPT, wenn man es betrunken bedient? __",
  "Was ruiniert jedes Teams-Meeting? __",
  "Was findet sich im Briefkasten meiner Schwiegermutter? __",
  "Was hat die KI heimlich über mich gelernt? __",
  "Was ist das Hauptproblem von Berlin-Kreuzberg? __",
  "Was hat meinen Mallorca-Urlaub ruiniert? __",
  "Was sagt mein Hausarzt nach dem Bluttest? __",
  "Was passiert in einer typischen Kreuzfahrtnacht? __",
  "Was hat das Bürgeramt mir verweigert? __",
  "Was ist mein größter TikTok-Trigger? __",
  "Was ist die Geheimzutat in Aldis Eigenmarke? __",
  "Was hat der Deutsche-Bahn-Kontrolleur entdeckt? __",
  "Was hat mich aus dem Schrebergartenverein geworfen? __",
  "Was ist der Inhalt vom ekligsten Aldi-Müsli? __",
  "Was darf bei einer schwäbischen Hochzeit nicht fehlen? __",
  "Was hat in meinem Tesla nicht funktioniert? __",
  "Was ist mein größter Kink in einer Beziehung? __",
  "Was ist der wahre Grund hinter meinem Burnout-Antrag? __",
  "Was hat das Pfarrhaus heimlich beherbergt? __",
  "Was kommt in meinem nächsten Bestseller-Buch vor? __",
  "Was ist der Top-Hit auf der Schlagerkreuzfahrt? __",
  "Worauf masturbiert ein KI-Forscher? __",
  "Was hat mein Hausverbot ausgelöst? __",
  "Was wäre meine Antwort, wenn der Papst fragt? __",
  "Was darf in keiner WG-Küche fehlen? __",
  "Was steht in der Stellenbeschreibung von Sahra Wagenknecht? __",
  "Was ist das größte Problem der Generation Alpha? __",
  "Was hat die Versicherung nicht abgedeckt? __",
  "Was kommt aus der Espressomaschine, wenn keiner hinsieht? __",
  "Womit erpresse ich meinen Schwiegervater? __",
  "Was ist der wahre Grund für die Inflation? __",
  "Was hat sich auf der Junggesellenabschieds-Tour selbständig gemacht? __",
  "Was war im Karton vom Online-Versand? __",
  "Was ist Helene Fischers Geheimrezept gegen Falten? __",
  "Was hat mir mein KI-Therapeut empfohlen? __",
  "Was hat sich Hape Kerkeling im Ruhestand zugelegt? __",
  "Was ist auf meinem letzten Klassenfoto zu sehen? __",
  "Was wird auf der EU-Klimakonferenz heimlich serviert? __",
  "Was findet ihr im Müll meiner WG? __",
  "Was ist das Geheimnis hinter Heidi Klums Casting-Auswahl? __",
  "Was hat mein Hund auf Drogen gemacht? __",
  "Was ist mein Albtraum-Trio bei Tinder? __",
  "Was kommt nach 2 Stunden Tatort und 3 Flaschen Rotwein? __",
  "Was hat Mama im Dezember in den Karton gelegt? __",
  "Was hat den Datenschutzbeauftragten zum Lachen gebracht? __",
  "Was steht in Friedrich Merz' geheimer Notiz an Habeck? __",
  "Was ist auf der Speisekarte vom Hamburger Hauptbahnhof um 3 Uhr? __",
  "Was hat das Influencer-Pärchen heimlich gepostet? __",
  "Was ist im Geheimfach des Pfarrers? __",
  "Was ist die wahre Identität des Verfassungsschutz-Mitarbeiters? __",
  "Wofür wurde mein Erbe ausgegeben? __",
  "Was hat mich aus dem Anglerverein geworfen? __",
  "Was hat mein Modelleisenbahn-Hobby ruiniert? __",
  "Was finde ich nach 3 Wochen in der Spülmaschine? __",
  "Was passiert im Saunaverein nach 22 Uhr? __",
  "Was ist Karl Lauterbachs Cocktail der Wahl? __",
  "Worauf läuft jede schwäbische Hochzeit hinaus? __",
  "Was hat mich beim Edeka-Kassenrolle-Geräusch erregt? __",
  "Womit erpresst die nächste Boomer-Generation ihre Eltern? __",
  "Was hat das Standesamt protokolliert? __",
  "Was findet ein Karpfenangler bei Vollmond? __",
  "Was hat sich auf der WG-Party heimlich entwickelt? __",
  "Was steht in den Lehrer-WhatsApp-Gruppen? __",
  "Was hat sich beim Yoga-Retreat selbständig gemacht? __",
  "Was findet man im Schrank eines überzeugten E-Auto-Fahrers? __",
  "Was steht in der Beschwerdebox vom Krankenhaus? __",
  "Was passiert beim Junggesellinnenabschied auf Mallorca? __",
  "Was hat den Erste-Hilfe-Kurs entgleisen lassen? __",
  "Was hat das Schwimmbad nach 22 Uhr nicht überlebt? __",
  "Was hat mich aus der katholischen Jugend geworfen? __",
  "Was kommt auf dem Schulausflug raus? __",
  "Was findet das Kind in Mamas Nachtschrank? __",
  "Was ist in der Stille der Kuhweide passiert? __",
  "Was ist in der Vatikan-Disko angesagt? __",
  "Was hat das Klassentreffen ruiniert? __",
  "Was ist die geheime Zutat im Lufthansa-Catering? __",
  "Was hat der Versicherungsvertreter im Wohnzimmer hinterlassen? __",
  "Was ist im Hintergrund auf meinem letzten Zoom-Call zu sehen? __",
  "Was kommt im SPD-Wahlkampfvideo vor? __",
  "Was hat mich aus dem Boxstudio fliegen lassen? __",
  "Was sagt mein Spiegelbild morgens um 5? __",
  "Was läuft auf der letzten Schlagerparty im Schwimmbad? __",
  "Was hat den Tatort aus 1987 unwiederholbar gemacht? __",
  "Was ist die Geheimwaffe der Bundeswehr? __",
  "Was hat sich nach Mitternacht in der Discounter-Filiale abgespielt? __",
  "Was steht im Geständnisbuch der Apotheken-Mitarbeiterin? __",
  "Was wäre das peinlichste Bewerbungs-Hobby? __",
  "Was ist der Star bei jeder Tupperparty? __",
  "Was ist in der TikTok-Bio meiner 14-jährigen Cousine? __",
  "Was hat das Reha-Zentrum dieses Jahr neu im Programm? __",
  "Was hat der Bauarbeiter unter dem Estrich gefunden? __",
  "Was darf in keinem Polit-Talkshow-Set fehlen? __",
  "Was hat der Kantinen-Koch ins Essen geschmuggelt? __",
  "Was ist in meinem ausgedruckten ChatGPT-Verlauf zu lesen? __",
  "Was ist Markus Söders neue Geschäftsidee? __",
  "Was hat Mama auf dem Familien-Spotify-Account angehört? __",
  "Was ist im Geschenkkorb meiner Schwiegereltern? __",
  "Was hat die WG-Versammlung eskalieren lassen? __",
  "Was hat mein erstes Online-Date für mich mitgebracht? __",
  "Was hat das Bürgermeister-Empfang nicht überlebt? __",
];

const whiteCards = [
  "Mein Therapeut",
  "Ein einsamer Pinguin im Lidl",
  "Hartz IV",
  "Eine Tüte alter Erinnerungen",
  "Der Tod höchstpersönlich",
  "Ein Glas Spreewaldgurken",
  "Karl-Heinz aus dem Schützenverein",
  "Heidi Klums Lächeln",
  "Drei Schluck Mundspülung",
  "Eine schlecht gelaunte Kassiererin",
  "Sex mit einem Föhn",
  "Die FDP",
  "Ein toter Hamster im Aquarium",
  "Helene Fischer auf Speed",
  "Die innere Leere",
  "Mein erster Kuss",
  "Eine Packung Toast",
  "Existenzielle Angst",
  "Der Klassenchat",
  "Olaf Scholz beim Twerken",
  "Eine peinliche Sprachnachricht",
  "Das Patriarchat",
  "Heimliches Saufen im Bürobad",
  "Eine fettige Tüte Pommes",
  "Onkel Manfred und sein Camper",
  "100 Stunden Tetris",
  "Ein nasser Gummibaum",
  "Schwangerschaftsstreifen",
  "Verstopfung",
  "Tante Hildes neue Brüste",
  "Wladimir Putin in Lederhosen",
  "Eine Wagner-Oper auf 1,5x",
  "Ein Zungenkuss von Boris Becker",
  "Eine Selbsthilfegruppe für Veganer",
  "Bionade",
  "Die Bundeswehr",
  "Das Lachen meiner Stiefmutter",
  "Eine offene Beziehung",
  "Hass",
  "Liebe (das Gefühl)",
  "Liebe (der Vorname)",
  "Eine Backofentür",
  "Schimmel auf altem Brot",
  "Eine Bauchnabelfussel-Sammlung",
  "Ein Reisebus voller Senioren",
  "Karl Lauterbach im Bademantel",
  "Ein versifftes Spülschwamm-Relikt",
  "Drogen",
  "Mehr Drogen",
  "Drei Bier zu viel",
  "Eine völlig überdrehte Yogalehrerin",
  "Mein Ex",
  "Eine kalte Currywurst",
  "Die deutsche Wiedervereinigung",
  "Ein extrem haariger Rücken",
  "Schweißfüße",
  "Eine schreiende Kreissäge",
  "Mama",
  "Ein Joint im Spülkasten",
  "Die Sparkasse",
  "Verdrängte Aggressionen",
  "Eine Ladung BWL-Studenten",
  "Ein bisschen zu viel Selbstliebe",
  "Eine peinliche Erektion",
  "Eine Bäckereifachverkäuferin mit Migräne",
  "Die Wechseljahre",
  "Ein Salzstreuer",
  "Globaler Atomkrieg",
  "Eine zu enge Latzhose",
  "Mein Rektalthermometer",
  "Ein kunstvoller Käseigel",
  "Eine Standpauke von Oma",
  "Spazierende Querdenker",
  "Mein neuer Tinder-Match",
  "Ein zugemüllter Fenstersims",
  "Drei Stunden YouTube-Tutorials",
  "Klein-Erna mit dem schiefen Auge",
  "Eine Verschwörung der Pinguine",
  "Mein Kindheitsteddy",
  "Eine durchgeknallte Pfarrerin",
  "Die Wahrheit",
  "Selbstgehäkelte Klopapierhalter",
  "Russisches Roulette beim Familienbrunch",
  "Ein Bierbauch in XXL",
  "Eine WhatsApp-Gruppe von Boomern",
  "Mein Gynäkologe",
  "Klorollen-Kunst",
  "Heimliche Wehmut",
  "Eine Sammlung aus Zahnseide",
  "Stinkende Joggingschuhe",
  "Mariä Himmelfahrt",
  "Eine Selbsthilfegruppe für Influencer",
  "Die Gesamtbevölkerung von Wuppertal",
  "Ein altes Pornoheft im Wald",
  "Ein peinliches Pseudonym",
  "Mein toxischer Freundeskreis",
  "Das Letzte Abendmahl",
  "Eine ASMR-Fußmassage",
  "Eine Krise der Männlichkeit",
  "Ein Facebook-Post von Mama",
  "Massive Übergriffigkeit",
  "Drei Schritte vor dem Burnout",
  "Eine Discoschlampe von 1989",
  "Mein zweites Konto",
  "Ein Bewerbungsgespräch ohne Hose",
  "Geistige Umnachtung",
  "Eine kleinkarierte Abrechnung",
  "Eine glitschige Aubergine",
  "Frühkindliche Verstörung",
  "Eine schreiende Babyrobbe",
  "Mein WG-Mitbewohner",
  "Vermisste Söckchen",
  "Eine Bestattung im Aldi",
  "Eine Kabbala-Zeremonie",
  "Das Wirtschaftswunder",
  "Mein Hausmeister",
  "Eine Influenza",
  "Eine durchgemachte Nacht",
  "Eine Affäre mit dem Postboten",
  "Eine Ladung Hipster aus Berlin",
  "Lebenslange Schuldgefühle",
  "Mein peinlicher Onkel",
  "Eine Abi-Klausur unter Drogen",
  "Verdrängung",
  "Eine kuriose Familienerbschaft",
  "Drei verschimmelte Mandarinen",
  "Ein Arbeitsamt-Termin",
  "Mein neues Hobby: Kotzen",
  "Existenzialismus",
  "Sneaker-Tanga",
  "Mein eigenes Spiegelbild",
  "Ein Schluck Aldi-Sekt",
  "Eine spirituelle Krise",
  "Großmutters Kompressionsstrümpfe",
  "Ein traumatisierter Goldfisch",
  "Eine Stunde mit dem Steuerberater",
  "Mein verlorener Verstand",
  "Eine Ladung Liebesbriefe von Klaus",
  "Mein Lieblingstrauma",
  "Eine Packung B-Promis",
  "Klimakatastrophe",
  "Mein Kontoauszug",
  "Eine Gruppe Krankenpfleger im Urlaub",
  "Hühnchen-Curry mit Reue",
  "Ein Schluck aus Opas Flachmann",
  "Mein Burnout",
  "Eine peinliche Tätowierung",
  "Drei Liter Eierlikör",
  "Mein erstes Mal",
  "Eine ausgeschlagene Erbschaft",
  "Verbalerotik",
  "Cancel Culture",
  "Mein Erbrochenes von gestern",
  "Ein peinliches Familiengeheimnis",
  "Eine Gruppe Schwiegermütter",
  "Ein Bratwurst-Imperium",
  "Mein Schmerzensgeld",
  "Eine Kollektivbestrafung",
  "Eine peinliche Karaoke-Performance",
  "Ein Date mit der Hauseigentümerin",
  "Ein abgelaufener Joghurt",
  "Drei Yogalehrer in einem Aufzug",
  "Mein 11-jähriges Tagebuch",
  "Ein verlassenes IKEA-Lager",
  "Eine Übermutter mit Drohne",
  "Drei Kilo Hummus",
  "Eine Ladung Wahlplakate",
  "Mein gesamtes Erspartes",
  "Eine Polizeikontrolle in Mallorca",
  "Eine Predigt auf Latein",
  "Ein verschüttetes Geheimnis",
  "Mein letztes Bewerbungsfoto",
  "Eine emotionale Erpressung",
  "Drei Dosen Ravioli",
  "Eine Krise mittleren Alters",
  "Ein Sektempfang ohne Sekt",
  "Mein versteckter Hass auf Geburtstage",
  "Ein leeres Konto mit Charme",
  "Eine Schwangerschaftsfeier in der Schule",
  "Ein versehentlicher Reply-All",
  "Mein WG-Putzplan",
  "Eine Ladung Dreitagebärte",
  "Friedrich Merz im Bonzenanzug",
  "Sahra Wagenknecht in Lederjacke",
  "Robert Habeck mit Kinderbüchern",
  "Christian Lindner im Porsche",
  "Markus Söder in Tracht",
  "Elon Musk auf Ketamin",
  "Donald Trump beim Sonnenbad",
  "Wladimir Putin oben ohne",
  "Greta Thunberg im Privatjet",
  "Der Papst im Whirlpool",
  "Helene Fischer ohne Make-up",
  "Pietro Lombardi als Nachhilfelehrer",
  "Michael Wendler im Knast",
  "Bushido beim Yoga",
  "Bibi und Julian beim Steuerberater",
  "Heidi Klum in der Klimax",
  "Joko und Klaas beim Burnout",
  "Hape Kerkeling als Drag Queen",
  "Til Schweiger nach dem Mittagsschlaf",
  "Florian Silbereisen am Steuer",
  "Mario Barth bei einer Frauenrechtsdemo",
  "Dieter Bohlen im Ehrenamt",
  "Hans-Werner Sinn am FKK-Strand",
  "Boris Pistorius ohne Hose",
  "Andrea Nahles beim Karneval",
  "Karl Marx mit Bitcoin-Wallet",
  "Friedrich Nietzsche im Strandbad",
  "Goethe auf Ozempic",
  "Beatrix von Storch im Tanzkurs",
  "Alice Weidel beim CSD",
  "Joschka Fischer auf Ecstasy",
  "Ein verschimmelter Adventskranz",
  "Eine zerquetschte Praline aus 2017",
  "Mein heiß geliebter Furby",
  "Ein vergessenes Kondom unter der Couch",
  "Mein erstes Vibrator-Geständnis",
  "Eine durchgekaute Bonbontüte",
  "Die Reste vom Silvesterbüfett",
  "Ein angeschlagenes Aldi-Schnitzel",
  "Mein staubiger Crosstrainer",
  "Eine Mausefalle mit Käse",
  "Ein durchnässter Wahlzettel",
  "Generationenkonflikt beim Sonntagsbraten",
  "Boomer-Logik in Reinkultur",
  "Gen-Z-Burnout",
  "Wokeness mit Bierbauch",
  "Mansplaining beim Sex",
  "Gaslighting von der Schwiegermutter",
  "Doomscrolling auf der Toilette",
  "Quiet Quitting im Pflegeheim",
  "Stille Resignation in der Beziehung",
  "Existenzielle Übermüdung",
  "Toxische Positivität auf LinkedIn",
  "Pleitegeist mit Hartz-IV-Antrag",
  "Spätsommerdepression",
  "Pubertät mit 40",
  "Premature Ejakulation am Hochzeitstag",
  "Sex auf der Tankstelle",
  "Ein Gangbang im Schrebergarten",
  "Eine Seance bei Kaufland",
  "Ein 70er-Jahre Swingerclub",
  "Vibratorensammeln als Hobby",
  "Onlinedating mit Oma",
  "Heimliches Googeln, was \"queer\" bedeutet",
  "Drei Stunden Bandscheibenprolaps",
  "Ein Drogentrip mit Spongebob",
  "Selbstbestätigung im Schminkspiegel",
  "Eine Erkundungstour im Chatbox-Bordell",
  "Mit dem Postboten kuscheln",
  "Heimlich saufen vor dem Bushido-Konzert",
  "Eine Buchhaltung im Bordell",
  "Ein verkrümmter Penis",
  "Ein 90-Sekunden-Sexrekord",
  "Ein zu sehr geweiteter Anus",
  "Verklemmte Männlichkeit",
  "Vorzeitige Ejakulation",
  "Eine Massage mit unerwartetem Ende",
  "Ein lautes \"Mama!\" beim Höhepunkt",
  "Ein BDSM-Beginner-Set",
  "Drei Liter Lubrikant",
  "Eine ungewollte Schwangerschaft",
  "Eine Verstopfung beim ersten Date",
  "Geriatrische Erotik",
  "Aldi-Lubrikant",
  "Ein Toupet mit Eigenleben",
  "Eine zusammenhanglose Erektion",
  "Schiefer Beckenboden",
  "Bauer sucht Frau, Bayern-Edition",
  "Eine Tatort-Folge mit Schimanski-Vibe",
  "Eine Galileo-Reportage über Currywurst",
  "Florian Silbereisens Nasenhaare",
  "Der dritte Mann von Helene Fischer",
  "Ein Heidi-Klum-GNTM-Casting",
  "DJ Ötzi auf Eis",
  "Ein Volksmusiksender im Free-TV",
  "Eine durchgeknallte Wetterfee",
  "Eine Currywurst mit Pommes Schranke",
  "Mein erster Vollrausch in der Pfarrei",
  "Vier Stunden Wartezeit beim Bürgeramt",
  "Eine Reichsbürger-Erklärung beim Frühstück",
  "Eine Razzia bei Familie Otten",
  "Mein Klassenfahrt-Tagebuch",
  "Mein Klassentreffen-Trauma",
  "Eine geheime Affäre mit der Pfarrerin",
  "Ein durchschwitzter Vibrator",
  "Eine Coronademo in der Pfalz",
  "Ein Atemschutzmaskenwald",
  "Mein peinlicher Songtext",
  "Eine ALG-II-Verlängerung",
  "Drei Stunden Wahlkampfbroschüren",
  "Ein Auftritt bei Markus Lanz",
  "Eine ARD-Brennpunkt-Sondersendung",
  "Eine Gruppe spazierender Reichsbürger",
  "Mein illegaler Mietvertrag",
  "Ein Kuhfladen mit Mehrwert",
  "Eine Pickelausquetsch-Session",
  "Eine ungeöffnete Mahnung",
  "Mein Steuerberater im Pyjama",
  "Vier vergeigte Diäten",
  "Eine WG-Küche nach Silvester",
  "Mein Spotify-Wrapped",
  "Eine Wodka-Familie",
  "Ein nasses Bett mit 35",
  "Mein Schamgefühl beim Frauenarzt",
  "Eine selbstgebrannte CD von 2003",
  "Mein Single-Profil bei Lovoo",
  "Eine Dating-App nur für Vegetarier",
  "Eine Gruppe Reisestressentladungstouristen",
  "Eine 3-Wochen-Magenverstimmung",
  "Eine Entzugsklinik in Bad Tölz",
  "Mein Onkel beim Junggesellenabschied",
  "Ein Schmierfilm auf der Brille",
  "Eine Buchsteuerprüfung",
  "Sex mit Kassenrolle",
  "Ein Tampon im Pool",
  "Drei Stunden BWL-Vorlesung",
  "Eine WhatsApp-Sprachnachricht von 9 Minuten",
  "Eine Krise nach 4 Bier",
  "Ein durchgehender Schluckauf",
  "Drei Buntstifte im Po",
  "Ein durchgeschwitzter Männerchor",
  "Eine Hochzeit zwischen Cousins",
  "Mein Geburtsfehler",
  "Eine Lehrerin auf MDMA",
  "Mein erster Sextoy",
  "Ein analytisches Gespräch mit dem Hund",
  "Mein heimlicher Hass auf Kinder",
  "Eine Beerdigung im Disco-Style",
  "Eine durchgemachte Klausurnacht",
  "Eine vergangene Schwangerschaft",
  "Mein Erstaugenkontakt mit Tante Renate",
  "Ein Dorfdiscokuss von 1998",
  "Eine ausgeartete Polonaise",
  "Mein letzter Cent",
  "Eine WG-Pilzkultur",
  "Mein gespaltener Mörderzeh",
  "Eine Ehe-Beratung mit der Lehrerin",
  "Mein Notfallspeck",
  "Drei abgekommene Beziehungen in einem Sommer",
  "Mein Coachingmaterial von 2018",
  "Eine Sportfreundschaft mit Folgen",
  "Mein heimlicher Hass auf Sport",
  "Eine zugedrückte Geschwürsblase",
  "Mein Geburtstagstrauma",
  "Eine 9-Liter-Eierlikör-Theke",
  "Mein Tinder-Match aus der Kirche",
  "Ein in Tüten gepackter Familienstreit",
  "Mein bourbon-getränkter Pyjama",
  "Eine Lebensmittelvergiftung beim Pfingstausflug",
  "Mein Erbrechen ins Schützenfest-Bier",
  "Eine Steuererklärung im Drogenrausch",
  "Mein peinlicher Schullkonzert-Auftritt",
  "Mein bestes Pseudonym auf OnlyFans",
  "Mein Bezugsmensch",
  "Mein größter Fail bei Mama",
  "Eine Eheschließung im Las Vegas-Suff",
  "Eine durchgeätzte Klobrille",
  "Eine durchgemachte Polonaise",
  "Eine missverstandene Massage",
  "Drei Schluck Augenbrauenmaske",
  "Eine fragwürdige Werbung im Kino",
  "Mein dauerhaft versumpfter Garten",
  "Mein bekanntester YouTube-Kommentar",
  "Eine durchgehängte Brust",
  "Eine vergessene Damenbinde",
  "Mein Ehestreit über Klopapier-Falten",
  "Eine WG-Mietabrechnung mit Excel-Drama",
  "Mein Hassbuch über die FDP",
  "Mein heimliches AfD-Sympathisanten-Outfit",
  "Mein blasses Gesicht nach dem Solotrip",
  "Mein 11. Bier",
  "Mein Ex und seine neue Freundin",
  "Eine WhatsApp-Affäre mit der Schwester",
  "Mein letzter Sexrekord (4 Sekunden)",
  "Mein vergessener Saugnapf",
  "Eine Yogamatte voller Geheimnisse",
  "Mein selbstgebauter Sextoy",
  "Eine peinliche Audionachricht an die ganze Klasse",
  "Mein heimliches Schwitzen unterm Talar",
  "Mein verlorener Reisepass in Bratislava",
  "Eine Fahrt mit dem Wuppertaler Rentnerverband",
  "Mein größter Fan auf Instagram (mein Vater)",
  "Eine in Folie eingeschweißte Pizza",
  "Mein Drogenkonsum mit 40",
  "Mein Lebensstrudel als Vegetarier",
  "Eine peinliche Penis-Pumpe",
  "Mein letzter Freistoßtor in der Kreisliga",
  "Mein Hass auf Geburtstagslieder",
  "Mein wackeliger Tatortmoderator",
  "Mein Affärenpartner mit Brille und Lispelfehler",
  "Mein durchgeschwitzter Konfirmationsanzug",
  "Drei Tüten Schimmel",
  "Eine Schwiegermutter mit Telegram-Account",
  "Eine durchgeknallte Yogalehrerin auf MDMA",
  "Eine Tunte mit Tatortverdacht",
  "Mein erster Tinder-Match (Profilbild von Onkel)",
  "Mein eigener Geruch auf Reisen",
  "Mein Lieblings-Klogang im Bürowohlfühlmodus",
  "Eine Whatsapp-Gruppe namens \"Trinkbrüder\"",
  "Eine Onlyfans-Premium-Mitgliedschaft",
  "Mein peinlichster Einkaufswagen",
  "Eine WhatsApp-Sprachnachricht meiner Mutter (12 Min)",
  "Mein 4-Tage-Rausch in Magaluf",
  "Mein neuer Dadbod",
  "Eine Affäre mit dem Schornsteinfeger",
  "Mein Atomkraftwerk-Fetisch",
  "Mein heimliches Faible für Putin",
  "Mein dritter Kaiserschnitt",
  "Mein erster Anal",
  "Mein Schreckenstraum vom Geburtstagsständchen",
  "Mein 7-jähriges Akne-Jubiläum",
  "Eine durchgeknallte Schwiegerschwester",
  "Mein durchgehender Schluckauf seit 2019",
  "Mein durchgesoffener Großonkel",
  "Mein Buchhaltungs-Burnout",
  "Mein Date mit der Lieferdienstfahrerin",
  "Mein Tabaksucht im Religionsunterricht",
  "Mein Penisbruch beim Pony reiten",
  "Mein hauseigener Genitalherpes",
  "Mein versteckter Whisky-Konsum im Kindergarten",
  "Mein 8-stündiger Fernsehmarathon",
  "Mein Date mit dem Imbissverkäufer",
  "Mein heimliches Lieblingslied von Helene Fischer",
  "Mein Sex am Sonntag in der Kirche",
  "Mein 12-jähriges Kuscheltier-Trauma",
  "Mein Liebesbrief an Lothar Matthäus",
  "Timmy der Wal",
  "Die Verwaltungsakademie Bordesholm",
  "Das Black Diamond in Bordesholm",
  "Herr Breetzke",
  "Der 127. Ang. II",
  "Sexy-Max",
  "Verwaltungsrecht",
  "Abendbrot in der VAB",
  "Eine ChatGPT-Halluzination",
  "Friedrich Merz' erste Amtsmonate",
  "Eine KI-generierte Fake-News",
  "Mein Spotify-Wrapped 2025",
  "Eine Tech-Entlassungswelle",
  "Donald Trumps zweite Amtszeit",
  "Eine Klimakonferenz ohne Ergebnis",
  "Eine Bürgergeld-Reform 2.0",
  "Ein 49-Euro-Ticket-Drama",
  "Eine TikTok-Verbotsdebatte",
  "Eine virale TikTok-Challenge",
  "Drei Stunden Teams-Meeting ohne Agenda",
  "Eine LinkedIn-Inspirationspost",
  "Mein durchgehängter Webcam-Filter",
  "Eine Telegram-Verschwörungsgruppe",
  "Ein deepgefakter Olaf Scholz",
  "Mein Reddit-Verlauf",
  "Ein KI-generiertes Liebesgedicht",
  "Mein Chef beim Casual Friday",
  "Eine peinliche Reply-All-Mail an die ganze Firma",
  "Mein Kalender mit 12 Sync-Calls",
  "Eine versehentliche Bildschirmfreigabe",
  "Ein Krankenschein vom Hausarzt mit Frage­zeichen",
  "Eine HR-Abteilung mit Drohgebärde",
  "Ein Praktikant mit Allmachtsfantasie",
  "Ein gestelltes Hinge-Profil",
  "Eine Bumble-Match nach 4 Bier",
  "Eine Beziehung mit Excel-Tabelle",
  "Mein Ghosting-Rekord (12 Personen)",
  "Eine Polyamorie-WG in Friedrichshain",
  "Ein Tinder-Like von der eigenen Cousine",
  "Eine Schlange beim Bürgeramt seit 4 Stunden",
  "Eine verlorene Steuererklärung",
  "Eine GEZ-Mahnung mit Pfändungsandrohung",
  "Drei Stunden DB-Verspätung bei Hannover",
  "Eine Polizeikontrolle in Berlin-Mitte",
  "Ein vergessenes Pfand in der Hose nach der Wäsche",
  "Eine Drogenkontrolle auf der A7",
  "Eine Bundesliga-Halbzeitanalyse mit Currywurst",
  "Mario Götze auf der Couch",
  "Ein WM-Pokal aus Plastik",
  "Mein Schalke-04-Trauma",
  "Drei Kilo schwäbischer Kartoffelsalat",
  "Eine vegane Currywurst",
  "Eine Tofu-Bratwurst von der Tankstelle",
  "Mein Spätzle-Hochzeitsbuffet",
  "Ein Weihnachtsbaum aus dem Lidl",
  "Eine Silvester-Rakete im Wohnzimmer",
  "Mein Karnevalskostüm 2007",
  "Eine Oma am Heiligabend nach 4 Likör",
  "Ein durchgesoffenes Osterfeuer",
  "Ein Mallorca-Pauschalurlaub mit der ganzen Familie",
  "Ein Camping-Klo in Schleswig-Holstein",
  "Eine Reise mit der Schwiegermutter",
  "Ein verlorener Reisepass in Kambodscha",
  "Ein Berlin-Kreuzberger Yoga-Studio",
  "Eine Schwabenfamilie beim Spätzle-Wettkampf",
  "Ein Sachsen-Stammtisch zur Mittagszeit",
  "Ein Reeperbahn-Junggesellinnenabschied",
  "Eine bayrische Lederhose nach drei Maß",
  "Eine BDSM-Couch aus dem Lidl",
  "Ein versehentlich gesendetes Nacktbild",
  "Eine sexuelle Phantasie über Andrea Berg",
  "Ein Sex-Toy aus 1989",
  "Eine Threesome mit Excel-Logistik",
  "Mein heimlicher Fußfetisch",
  "Eine Gen-Alpha-TikTok-Karriere",
  "Mein Boomer-Onkel mit Faxgerät",
  "Eine Gen-Z mit Existenzkrise",
  "Meine Millennial-Avocado-Toast-Obsession",
  "Eine Pfarrerin auf Tinder",
  "Der heimliche Wein-Vorrat im Beichtstuhl",
  "Mein Burnout-Bilderbuch",
  "Eine Selbsthilfegruppe für Influencer in Krise",
  "Mein Antidepressivum mit Aldi-Logo",
  "Eine Panikattacke beim Edeka",
  "Meine 7. Burnout-Karenz",
  "Eine Therapeutin mit 9 Monaten Warteliste",
  "Ein Kühlschrank voller Bockwurst",
  "Eine Rumba mit dem Postboten",
  "Mein peinlichstes Spotify-Wrapped (Helene Fischer)",
  "Eine durchgeknallte Apothekerin mit Diazepam",
  "Ein Pinguin im Spreewald",
  "Eine illegale Massage am Bahnhof",
  "Mein Tinder-Date mit der Klassenlehrerin",
  "Eine Volksmusik-Polka beim Bestatter",
  "Ein Esoterik-Workshop in Mecklenburg",
  "Eine Reichsbürger-Familie mit Camping-Bus",
  "Mein 49-Euro-Ticket nach Hannover (Stornogebühr)",
  "Eine Drogenrazzia im Schrebergarten",
  "Eine Sex-Party im Saunaverein",
  "Ein deutscher Schäferhund mit Wutproblem",
  "Eine Kollegin mit zu viel Eau de Toilette",
  "Mein Cousin mit Rotwein-Fleck auf der Hochzeit",
  "Eine WG-Putz-Liste in Excel",
  "Mein bestes Witz beim Vorstellungsgespräch",
  "Eine peinliche Sprachnachricht an den Ex",
  "Drei Pizzen aus dem Aldi-Tiefkühler",
  "Mein letzter Kühlschrank-Fund (2022)",
  "Eine Yogamatte mit Kotz-Spuren",
  "Mein gefälschtes Doktortitel",
  "Eine durchgemachte ICE-Fahrt mit Schlafanzug",
  "Eine Affäre mit dem Apple-Genius",
  "Mein letzter ungeschickter Sex-Versuch",
  "Eine Pyramide aus leeren Aldi-Sekt-Flaschen",
  "Mein toxischer Selbstoptimierungs-Plan",
  "Eine WhatsApp-Affäre mit dem Klassenkameraden",
  "Drei Schluck altes Hustensaft",
  "Mein Penis als Mascot-Figur",
  "Eine Friedrich-Merz-Stilberatung",
  "Ein durchgesickerter Habeck-Tweet",
  "Eine Sahra-Wagenknecht-Doku in 7 Teilen",
  "Ein FDP-Sektempfang mit Pizza-Tarif",
  "Eine AfD-Kandidatin im Yoga-Studio",
  "Eine Bundeswehr mit Schlafanzug-Uniform",
  "Der Verfassungsschutz im Wickelkleid",
  "Eine Mischpille aus drei verschiedenen Apotheken",
  "Mein Pilztrip auf Mallorca",
  "Eine Line Speed im Bürgeramt",
  "Drei Wochen Entzug im Allgäu",
  "Mein erstes Mal kiffen mit Mama",
  "Eine Ketamin-Therapie in München",
  "Eine Volltrunkenheit beim Vorstellungsgespräch",
  "Eine versehentliche Selbstbefriedigung in der Bahn",
  "Mein Sextoy mit USB-Anschluss",
  "Ein Vibrator aus dem Lidl-Sale",
  "Eine analytische BDSM-Beziehung",
  "Eine Massage-Therapeutin mit Lizenz zum Anfassen",
  "Mein Threesome am Familientisch",
  "Eine peinliche Pornofilm-Vorführung in der WG",
  "Mein erstes Femdom-Erlebnis",
  "Eine Webby-Award-Verleihung mit Bushido",
  "Mein heimlicher Crypto-Verlust",
  "Eine NFT von meinem Hund",
  "Eine Twitch-Streamerin mit Tic",
  "Mein OnlyFans-Selfie",
  "Eine Discord-Gruppe für Reichsbürger",
  "Mein Suchverlauf, durchgesickert auf Bild.de",
  "Eine virale Twerk-Challenge mit Olaf Scholz",
  "Mein eigenes Begräbnis als TikTok-Live",
  "Eine Selbstmord-Hotline mit Wartezeit",
  "Mein letzter Wille (Spotify-Wrapped)",
  "Eine Beerdigung im Aldi-Discounter",
  "Mein Trauerredner mit Lispel",
  "Eine offene Grabrede vom Ex",
  "Ein Goldhamster mit Diabetes",
  "Drei Kaninchen mit Identitätskrise",
  "Mein Wellensittich mit Helene-Fischer-Repertoire",
  "Eine Katze mit Burnout",
  "Ein Hund mit Anwalt",
  "Til Schweiger nach dem Mittagsschnaps",
  "Pietro Lombardi nach 5 Sangria",
  "Eine Beatrice-Egli-Karaoke-Performance",
  "Eine Veronica Ferres mit Botox-Fail",
  "Eine Verona Pooth mit Excel-Tabelle",
  "Der Wendler im Wohnwagen",
  "Ein Karpfenangler mit Selbstgespräch",
  "Ein Modelleisenbahn-Club mit Affäre",
  "Eine Sammelleidenschaft für gebrauchte Bahncards",
  "Eine Briefmarken-Auktion im Darknet",
  "Mein Pfeil-und-Bogen-Hobby im Schrebergarten",
  "Eine Achselrasur mit Senf",
  "Mein bestes Furzkonzert in der Schule",
  "Ein eingewachsener Zehnagel",
  "Drei Liter Magensäure am Morgen",
  "Eine gequetschte Hämorrhoide",
  "Mein Pickelbuch mit Vorher-Nachher-Fotos",
  "Eine Furunkel-Operation im Wohnzimmer",
  "Eine Hochzeit mit Ausnüchterungszelle",
  "Mein Brautstrauß aus Apothekenresten",
  "Eine Trauzeugin mit Schweißausbruch",
  "Ein Brautvater im Talar",
  "Ein DDR-Plattenbau mit Sauna",
  "Eine Stasi-Akte über meinen Opa",
  "Mein Trabant mit Tuning-Heckspoiler",
  "Eine Wessi-Ossi-Ehe nach 30 Jahren",
  "Ein Döner mit Käse und Ananas",
  "Eine Schwarzwälder Kirschtorte mit Rotwein-Glasur",
  "Eine Pizzakarton-Sammlung von 2020",
  "Eine Currywurst mit Pommes Rot-Weiß und Reue",
  "Eine Erbsensuppe nach 5 Tagen",
  "Mein Konzept-Papier für die Geschäftsführung",
  "Eine PowerPoint mit Comic Sans",
  "Eine Excel-Tabelle ohne Speichern (4 Stunden Arbeit weg)",
  "Mein Kollege mit lautem Kauen",
  "Ein Headset mit Kabelbruch",
  "Eine Aida-Kreuzfahrt voller Senioren mit Walkie-Talkies",
  "Ein Ferienhaus in Kroatien ohne Strom",
  "Eine Pauschalreise mit der Schwiegermutter nach Antalya",
  "Eine Pyramide aus Gummibärchen-Schachteln",
  "Mein Kaktus mit Persönlichkeitsstörung",
  "Eine Apokalypse mit ALDI-Werbeprospekt",
  "Eine Volkshochschule-Reisetour mit Kondom-Pause",
  "Eine Verschwörung auf der Volkshochschule",
  "Mein Ersatzleben in einer Sims-Familie",
  "Ein verstauchter Fußnagel beim Discotanz",
  "Eine Massage mit der WG-Mitbewohnerin",
  "Eine Hochzeitsnacht ohne Vollzug",
  "Ein Kühlschrank-Tinder-Match",
  "Mein Date in einer Reha-Klinik",
  "Heidi Reichinnek beim Schreien",
  "Janine Wissler im Yoga-Look",
  "Bodo Ramelow nach 2 Köstritzer",
  "Cem Özdemir im Bio-Bauernhof",
  "Markus Lanz nach 4 Stunden Sendung",
  "Anne Will beim Online-Dating",
  "Klaas Heufer-Umlauf mit Burnout",
  "Detlev Buck im Kleinwagen",
  "Anna-Maria Zimmermann nach 5 Korn",
  "Pocher und Knossi auf Crack",
  "Verona Pooth ohne Schminke",
  "Stefan Raab als Putzkraft",
  "Eine Wassergeburt auf dem Penny-Parkplatz",
  "Drei Stunden Erste-Hilfe mit Zungenkuss",
  "Eine Vatikan-Disko mit Schlagermusik",
  "Ein Schwimmbadgottesdienst",
  "Eine Beichte im Drive-Thru",
  "Ein Klassentreffen mit DNA-Test",
  "Eine Tupperparty mit Pole-Tanz",
  "Mein Bewerbungsgespräch im Bademantel",
  "Eine Selbstfindungsreise nach Brandenburg",
  "Drei Tage Hartz-IV-Bürokratie-Loop",
  "Ein Schulausflug mit Polizei-Eskorte",
  "Eine selbstgemachte Bombe aus Aldi-Sekt",
  "Eine Tampon-Schleuder fürs Schulfest",
  "Eine Sammlung getrockneter Spinnen",
  "Eine Plastikflasche voller Tränen",
  "Drei Liter Hustenmittel aus dem Darknet",
  "Eine illegale Cousins-Hochzeit",
  "Mein vergessener USB-Stick mit Steuersünden",
  "Eine Klingelbeutel-Sammlung der Pfarrei",
  "Eine Pickelparade auf dem Bewerbungsfoto",
  "Mein dauerhaft schiefes Lächeln nach dem Botox",
  "Eine Magenspülung an Heiligabend",
  "Eine Hämorrhoiden-OP mit Live-Stream",
  "Drei Furze im Aufzug",
  "Ein Quickie im Zugklo",
  "Mein heimliches Excel zu Sexstellungen",
  "Eine FKK-Sauna mit Schwiegervater",
  "Ein One-Night-Stand mit dem Penny-Kassierer",
  "Mein heimliches Faible für Senioren",
  "Eine versehentliche Penisparade im Familienpool",
  "Drei Wochen schmerzhafte Erektion",
  "Mein KI-generiertes Selbstporträt",
  "Eine Twitter-Beleidigung gegen die Bundesregierung",
  "Ein viraler Stinktier-Clip auf TikTok",
  "Mein iPhone-Akkustand bei 2%",
  "Eine Sprachnachricht von 18 Minuten",
  "Ein Discord-Server für Anti-Anti-Veganer",
  "Mein Chef beim Yoga-Selfie",
  "Eine HR-Mail mit 6 Smileys",
  "Drei Stunden Onboarding-Video",
  "Mein Kollege mit chronischem Mundgeruch",
  "Eine Beförderung wegen Sympathie",
  "Mein Vater mit OnlyFans-Account",
  "Mama beim Speed-Dating",
  "Eine Stiefmutter mit Drohne",
  "Mein Bruder als Influencer im Schrebergarten",
  "Tante Hilde mit Cannabis-Anbau",
  "Mein Lehrer mit Rotweinglas im Klassenraum",
  "Eine Abi-Klausur mit Drogenkontrolle",
  "Mein Direktor beim Pole-Dance",
  "Eine Sex-Aufklärungsstunde mit Live-Demo",
  "Eine Klassenfahrt mit Kondomausgabe",
  "Eine Verkehrskontrolle mit Eichmaß",
  "Mein Tesla mit Vollbremsung auf der Autobahn",
  "Drei Stunden Stau mit Vollblase",
  "Mein Carsharing-Auto wieder auf eBay-Kleinanzeigen",
  "Ein falsch übersetzter Bibelvers",
  "Mein Steuerberater im Bademantel",
  "Eine WG-Sauna nach 4 Bier",
  "Drei Liter Glühwein vom Bürgermeister",
  "Eine Plastikrose vom Tankstellen-Date",
  "Ein Lebenslauf voller Lügen",
  "Eine WG-Putzplan-Eskalation",
  "Drei Wochen Kokain-Detox",
  "Eine illegale Pyramidenfeier",
  "Mein Lieblings-Online-Casino",
  "Eine Affäre mit dem Schwager",
  "Ein zerbrochener Vibrator im Aldi-Korb",
  "Eine durchgemachte Karaoke-Nacht in Ulm",
  "Mein bester Junggesellinnenabschied (Penny-Parkplatz)",
  "Eine Drohne mit Voyeur-Programm",
  "Mein FKK-Tinder-Profil",
  "Eine Wodka-Schlacht im Pfarrhof",
  "Mein Boss mit ADHS und 8 Espresso",
  "Eine Beziehung aus dem Tarot-Buch",
  "Eine 14-jährige TikTok-Diva",
  "Mein 11. Fitnessstudio-Vertrag",
  "Eine Karnevalsumzugs-Ausschreitung",
  "Mein selbstgebautes Cybertruck-Modell",
  "Eine WG-Beziehung mit drei Personen",
  "Mein schwitziger Handabdruck auf der U-Bahn-Stange",
  "Eine peinliche Fortbildung in Bielefeld",
  "Mein Kollege mit Sandalen und Strümpfen",
  "Eine geheime Affäre auf dem Dienst-Tagesausflug",
  "Mein Schwiegervater mit Lautstärkeproblem",
  "Eine Senioren-Cruise mit Discokugel",
  "Mein peinlicher Tatort-Spoiler",
];

module.exports = { blackCards, whiteCards };
