// Eigener Karten-Pool. __ markiert die Lücke, die durch die gespielte weiße Karte ersetzt wird.
// Falls keine Lücke vorhanden ist, wird die Antwort hinten drangehängt.

const blackCards = [
  "Was steckt hinter Tür Nummer 3? __",
  "Worüber sollte mein TED Talk gehen? __",
  "Was ist die wahre Ursache des Klimawandels? __",
  "Was bringt jede Familienfeier zum Eskalieren? __",
  "Was würde Mama niemals zugeben? __",
  "Was steht heimlich in meinem Lebenslauf? __",
  "Was hat mich aus dem Schützenverein fliegen lassen? __",
  "Was finde ich entspannender als Yoga? __",
  "Was war der Grund für meine Scheidung? __",
  "Was ist das hässlichste Geschenk, das ich je bekommen habe? __",
  "Wovor fürchten sich kleine Kinder zurecht? __",
  "Was ist das neue Statussymbol der Boomer? __",
  "Mein Therapeut sagt, ich habe ein Problem mit __.",
  "Was hat es nicht in den Bibel-Cut geschafft? __",
  "Was geht mir auf einer Beerdigung durch den Kopf? __",
  "Worauf bin ich seit Jahren süchtig? __",
  "Was wirft Oma immer in den Wäschetrockner? __",
  "Was hat die Bundeswehr aus mir gemacht? __",
  "Was würde Jesus heute zur Begrüßung sagen? __",
  "Was steht ganz oben auf der To-Do-Liste eines mittelmäßigen Bösewichts? __",
  "Was hat das Christkind dieses Jahr unterm Baum vergessen? __",
  "Was ist der wahre Sinn des Lebens? __",
  "Was sollte definitiv NICHT auf einer Hochzeitstorte stehen? __",
  "Was ist das nächste große Dating-App-Feature? __",
  "Was würde Olaf Scholz auf seine Visitenkarte drucken? __",
  "Was ist deutscher als Bratwurst? __",
  "Was kommt als Nächstes auf Netflix? __",
  "Was bringt mich morgens aus dem Bett? __",
  "Was hat Hape Kerkeling in seiner Garage versteckt? __",
  "Was war früher besser? __",
  "Was hat mein Schwiegervater nach drei Jägermeister gestanden? __",
  "Was ist das echte Geheimnis hinter der Pyramidenform? __",
  "Was hilft gegen Schluckauf? __",
  "Womit erpresse ich meinen Bruder? __",
  "Was steht im Tagebuch von Markus Söder? __",
  "Was sollte man nicht vor Kindern sagen? __",
  "Was riecht im Lehrerzimmer? __",
  "Was hat sich nach dem fünften Glühwein selbständig gemacht? __",
  "Was ist Heidi Klums neuestes Hobby? __",
  "Was ist der Grund, warum ich heute zu spät bin? __",
  "Was hat mein Hund gestern gegessen? __",
  "Was würde mich sofort zum YouTube-Star machen? __",
  "Mein Kindheitstrauma: __.",
  "Was hat den letzten Bachelor-Cast überzeugt? __",
  "Was ist die geheime Zutat in Großmutters Kuchen? __",
  "Was ist im Universum eines Vier-Sterne-Generals normal? __",
  "Was bedeutet \"deutsche Gemütlichkeit\"? __",
  "Was hat den Fall der Berliner Mauer wirklich ausgelöst? __",
  "Was ist der wahre Grund, warum ich keinen Sex mehr habe? __",
  "Was sollte unbedingt in jedes Schulgebet aufgenommen werden? __",
  "Was würde ich tun, wenn ich für einen Tag unsichtbar wäre? __",
  "Was ist das Problem mit der jüngeren Generation? __",
  "Was sehe ich, wenn ich die Augen schließe? __",
  "Was steht auf meinem Grabstein? __",
  "Eine Sache, die jedes Erstdate ruiniert: __.",
  "Mein größter Fehler war __.",
  "Was hat der Papst Donnerstag gemacht? __",
  "Was ist der Grund für mein soziales Unbehagen? __",
  "Auf was würde ich für 10 Euro verzichten? __",
  "Was ist die wahre Ursache für meinen Burnout? __",
];

const whiteCards = [
  "Mein Therapeut",
  "Ein einsamer Pinguin im Lidl",
  "Hartz IV",
  "Eine Tüte alter Erinnerungen",
  "Der Tod höchstpersönlich",
  "Ein Glas Spreewaldgurken",
  "Karl-Heinz aus dem Schützenverein",
  "Heidi Klums Lächeln",
  "Drei Schluck Mundspülung",
  "Eine schlecht gelaunte Kassiererin",
  "Sex mit einem Föhn",
  "Die FDP",
  "Ein toter Hamster im Aquarium",
  "Helene Fischer auf Speed",
  "Die innere Leere",
  "Mein erster Kuss",
  "Eine Packung Toast",
  "Existenzielle Angst",
  "Der Klassenchat",
  "Olaf Scholz beim Twerken",
  "Eine peinliche Sprachnachricht",
  "Das Patriarchat",
  "Heimliches Saufen im Bürobad",
  "Eine fettige Tüte Pommes",
  "Onkel Manfred und sein Camper",
  "100 Stunden Tetris",
  "Ein nasser Gummibaum",
  "Schwangerschaftsstreifen",
  "Verstopfung",
  "Tante Hildes neue Brüste",
  "Wladimir Putin in Lederhosen",
  "Eine Wagner-Oper auf 1,5x",
  "Ein Zungenkuss von Boris Becker",
  "Eine Selbsthilfegruppe für Veganer",
  "Bionade",
  "Die Bundeswehr",
  "Das Lachen meiner Stiefmutter",
  "Eine offene Beziehung",
  "Hass",
  "Liebe (das Gefühl)",
  "Liebe (der Vorname)",
  "Eine Backofentür",
  "Schimmel auf altem Brot",
  "Eine Bauchnabelfussel-Sammlung",
  "Ein Reisebus voller Senioren",
  "Karl Lauterbach im Bademantel",
  "Ein versifftes Spülschwamm-Relikt",
  "Drogen",
  "Mehr Drogen",
  "Drei Bier zu viel",
  "Eine völlig überdrehte Yogalehrerin",
  "Mein Ex",
  "Eine kalte Currywurst",
  "Die deutsche Wiedervereinigung",
  "Ein extrem haariger Rücken",
  "Schweißfüße",
  "Eine schreiende Kreissäge",
  "Mama",
  "Ein Joint im Spülkasten",
  "Die Sparkasse",
  "Verdrängte Aggressionen",
  "Eine Ladung BWL-Studenten",
  "Ein bisschen zu viel Selbstliebe",
  "Eine peinliche Erektion",
  "Eine Bäckereifachverkäuferin mit Migräne",
  "Die Wechseljahre",
  "Ein Salzstreuer",
  "Globaler Atomkrieg",
  "Eine zu enge Latzhose",
  "Mein Rektalthermometer",
  "Ein kunstvoller Käseigel",
  "Eine Standpauke von Oma",
  "Spazierende Querdenker",
  "Mein neuer Tinder-Match",
  "Ein zugemüllter Fenstersims",
  "Drei Stunden YouTube-Tutorials",
  "Klein-Erna mit dem schiefen Auge",
  "Eine Verschwörung der Pinguine",
  "Mein Kindheitsteddy",
  "Eine durchgeknallte Pfarrerin",
  "Die Wahrheit",
  "Selbstgehäkelte Klopapierhalter",
  "Russisches Roulette beim Familienbrunch",
  "Ein Bierbauch in XXL",
  "Eine WhatsApp-Gruppe von Boomern",
  "Mein Gynäkologe",
  "Klorollen-Kunst",
  "Heimliche Wehmut",
  "Eine Sammlung aus Zahnseide",
  "Stinkende Joggingschuhe",
  "Mariä Himmelfahrt",
  "Eine Selbsthilfegruppe für Influencer",
  "Die Gesamtbevölkerung von Wuppertal",
  "Ein altes Pornoheft im Wald",
  "Ein peinliches Pseudonym",
  "Mein toxischer Freundeskreis",
  "Das Letzte Abendmahl",
  "Eine ASMR-Fußmassage",
  "Eine Krise der Männlichkeit",
  "Ein Facebook-Post von Mama",
  "Massive Übergriffigkeit",
  "Drei Schritte vor dem Burnout",
  "Eine Discoschlampe von 1989",
  "Mein zweites Konto",
  "Ein Bewerbungsgespräch ohne Hose",
  "Geistige Umnachtung",
  "Eine kleinkarierte Abrechnung",
  "Eine glitschige Aubergine",
  "Frühkindliche Verstörung",
  "Eine schreiende Babyrobbe",
  "Mein WG-Mitbewohner",
  "Vermisste Söckchen",
  "Eine Bestattung im Aldi",
  "Eine Kabbala-Zeremonie",
  "Das Wirtschaftswunder",
  "Mein Hausmeister",
  "Eine Influenza",
  "Eine durchgemachte Nacht",
  "Eine Affäre mit dem Postboten",
  "Eine Ladung Hipster aus Berlin",
  "Lebenslange Schuldgefühle",
  "Mein peinlicher Onkel",
  "Eine Abi-Klausur unter Drogen",
  "Verdrängung",
  "Eine kuriose Familienerbschaft",
  "Drei verschimmelte Mandarinen",
  "Ein Arbeitsamt-Termin",
  "Mein neues Hobby: Kotzen",
  "Existenzialismus",
  "Sneaker-Tanga",
  "Mein eigenes Spiegelbild",
  "Ein Schluck Aldi-Sekt",
  "Eine spirituelle Krise",
  "Großmutters Kompressionsstrümpfe",
  "Ein traumatisierter Goldfisch",
  "Eine Stunde mit dem Steuerberater",
  "Mein verlorener Verstand",
  "Eine Ladung Liebesbriefe von Klaus",
  "Mein Lieblingstrauma",
  "Eine Packung B-Promis",
  "Klimakatastrophe",
  "Mein Kontoauszug",
  "Eine Gruppe Krankenpfleger im Urlaub",
  "Hühnchen-Curry mit Reue",
  "Ein Schluck aus Opas Flachmann",
  "Mein Burnout",
  "Eine peinliche Tätowierung",
  "Drei Liter Eierlikör",
  "Mein erstes Mal",
  "Eine ausgeschlagene Erbschaft",
  "Verbalerotik",
  "Cancel Culture",
  "Mein Erbrochenes von gestern",
  "Ein peinliches Familiengeheimnis",
  "Eine Gruppe Schwiegermütter",
  "Ein Bratwurst-Imperium",
  "Mein Schmerzensgeld",
  "Eine Kollektivbestrafung",
  "Eine peinliche Karaoke-Performance",
  "Ein Date mit der Hauseigentümerin",
  "Ein abgelaufener Joghurt",
  "Drei Yogalehrer in einem Aufzug",
  "Mein 11-jähriges Tagebuch",
  "Ein verlassenes IKEA-Lager",
  "Eine Übermutter mit Drohne",
  "Drei Kilo Hummus",
  "Eine Ladung Wahlplakate",
  "Mein gesamtes Erspartes",
  "Eine Polizeikontrolle in Mallorca",
  "Eine Predigt auf Latein",
  "Ein verschüttetes Geheimnis",
  "Mein letztes Bewerbungsfoto",
  "Eine emotionale Erpressung",
  "Drei Dosen Ravioli",
  "Eine Krise mittleren Alters",
  "Ein Sektempfang ohne Sekt",
  "Mein versteckter Hass auf Geburtstage",
  "Ein leeres Konto mit Charme",
  "Eine Schwangerschaftsfeier in der Schule",
  "Ein versehentlicher Reply-All",
  "Mein WG-Putzplan",
  "Eine Ladung Dreitagebärte",
];

module.exports = { blackCards, whiteCards };
